### PR TITLE
Fixing deployAEScenario method. It was using wrong path of the API. N…

### PR DESCRIPTION
**Pull request by JeanValjean17**
…ow it takes the scenario name input and writes it into a json and post it to: /platform-ctrl/v1/sandboxes. This creates a new sandbox with a random generated name, and deploys the scenario.

### CODE REVIEW

**Review by juan-castrillon — COMMENTED** [review]
Hey @JeanValjean17 !

Is there any specific reason to why we need it wrapped in a sandbox, instead of just deploying the scenario? Because for just that, the path [was right](https://github.com/InterDigitalInc/AdvantEDGE/wiki/api-sandbox-ctrl#activename), it just required the scenario to be in the scenario store first (added).

Also, and this is because I really dont know it and maybe you have more experience, is it necessary to add the "/platform-ctrl/v1/" part ?, given that the API specification just mentions the path like "/sandboxes" or "/active"

**Comment by alyhasansakr** [comment]
@juan-castrillon Sandboxes is a feature that was added recently, it is more generalized than having a single active scenario at a given time, so I would say we go with the sandboxes better.

About the exact path, of course you have to test it just to be sure, but you normally find it in the swagger file with the tag "basePath", that is why they may not mention it in a wiki page.

So try it and see if the new path is correct.

**Comment by juan-castrillon** [comment]
@alyhasansakr You are right, so I will approve these changes and also then correct the other paths (for creating and terminanting scenarios) by adding the base URL

**Review by juan-castrillon — APPROVED** [review]

**Comment by juan-castrillon** [comment]
My last commits are failing the test for something competely unrelated to what I modified: 

> InfrastructureManager.RestFunctionalTests > classMethod FAILED
    java.lang.Exception at RestFunctionalTests.java:24

I believe, it has something to do with the github worker, because locally, the test pass

**Comment by alyhasansakr** [comment]
@juan-castrillon 
Not sure if this is the problem but it is a problem nevertheless, in the file RestFunctionalTests.java you are using getRestRunner() without parameters, that would throw an exception if there no RestRunner instance is created, instead use getRestRunner(String name, int port) that should create an instance in this case.

As for why it fails on the worker and not on your machine, if this is the problem then it has to do with the order of tests execution (if RestRunner was created before, it will not throw an exception here).

Fix that and lets see if it still fails.

**Review by juan-castrillon — APPROVED** [review]

**Comment by juan-castrillon** [comment]
@alyhasansakr That was the problem, thanks a lot! Weird that it just pops up now, but now, the branch is ready to be merged, so i will do that

**Pull request merged**
